SOURCES=base.cpp num.cpp ref.cpp name.cpp string.cpp array.cpp dict.cpp ptr.cpp

CPPFLAGS=-O3 -funroll-all-loops -finline-functions -Wall -g
LDFLAGS=

CPPFLAGS+=-I../../../lsyscpp
ADDOBJS+=../../../lsyscpp/exception.o ../../../lsyscpp/filesystem.o

include ../std.mk
